
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# Insteon ISY Integration
#isy994:
#  host: http://192.168.1.4:80
#  username: !secret isy_username
#  password: !secret isy_password
# Elk M1
elkm1:
  - host: elk://192.168.1.251
    area:
      exclude: [2-8]
    zone:
      exclude: [3-16, 27-208]
    plc:
      exclude: [a4-p16]
    task:
      exclude: [2-32]
    counter:
      exclude: [1-64]
    keypad:
      exclude: [2-16]
    setting:
      exclude: [1-20]
    output:
      enabled: false
    thermostat:
      enabled: false
# Honeywell Thermostat
climate:
  - platform: honeywell
    username: !secret honeywell_username
    password: !secret honeywell_password
    region: us
